@echo off
echo Clearing npm cache...
npm cache clean --force
echo Deleting node_modules...
rd /s /q node_modules
echo Deleting package-lock.json...
del package-lock.json
echo Installing dependencies...
npm install
echo Installing vite react plugin...
npm install @vitejs/plugin-react --save-dev
echo Done!