@echo off
echo Adding all changed files...
git add .

echo Creating commit...
git commit -m "feat: Major assessment improvements and bug fixes" -m "- Fixed MMT & ROM assessments with correct color mapping" -m "- Implemented form reset functionality for new assessments" -m "- Enhanced pain assessment integration" -m "- Improved data synchronization between components" -m "- Updated documentation with recent changes" -m "- Fixed dialog error handling and exports" -m "- Enhanced UI feedback and validation" -m "- Synchronized component state management" -m "- Added extensive debug logging" -m "- Fixed component exports and imports"

echo Pushing to version-2.0...
git push origin version-2.0