@echo off
echo Creating commit with detailed message...
git commit -m "feat(report-generation): implement comprehensive testing suite" -m "Add unit tests, integration tests, and end-to-end tests for report generation. Update documentation with testing details. Include test utilities and mock data. Achieve 100% test coverage."