@echo off
echo Running narrative tests with coverage...
call npm test src/components/ReportGeneration/agents/__tests__/BaseAgent.test.ts src/components/ReportGeneration/testing/TestableAgent.test.ts --coverage