// ... all the imports stay the same ...

// ... all the constants stay the same ...

function HousekeepingSection() {
  // ... component implementation stays the same ...
}

export default HousekeepingSection;