export const generalSymptoms = [
  { id: "dizziness", label: "Dizziness" },
  { id: "vertigo", label: "Vertigo" },
  { id: "nausea", label: "Nausea" },
  { id: "vomiting", label: "Vomiting" },
  { id: "photophobia", label: "Light Sensitivity" },
  { id: "phonophobia", label: "Sound Sensitivity" },
  { id: "smell_sensitivity", label: "Sensitivity to Smells" },
  { id: "fatigue", label: "Fatigue" },
  { id: "sleep_disturbance", label: "Sleep Disturbance" },
  { id: "headache", label: "Headache" },
  { id: "vision_changes", label: "Vision Changes" },
  { id: "hearing_changes", label: "Hearing Changes" },
  { id: "ringing_ears", label: "Ringing in Ears" },
  { id: "balance_issues", label: "Balance Issues" },
  { id: "appetite_changes", label: "Appetite Changes" },
  { id: "gi_issues", label: "Gastrointestinal Issues" },
  { id: "mood_changes", label: "Mood Changes" },
  { id: "anxiety", label: "Anxiety" },
  { id: "depression", label: "Depression" }
];