name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    - name: Run container scan
      uses: azure/container-scan@v0
      with:
        image-name: ${{ github.repository }}:${{ github.sha }}

    - name: Run OWASP ZAP scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: 'http://localhost:8080'

    - name: Create security report
      if: always()
      run: |
        echo "## Security Scan Results" > security-report.md
        echo "### Scan completed at: $(date)" >> security-report.md
        echo "\nDetailed results can be found in the workflow artifacts." >> security-report.md

    - name: Upload security report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: security-report.md

    - name: Notify security issues
      if: failure()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: 'security-alerts'
        slack-message: 'Security vulnerabilities detected! Check the report: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}